Decode Morse
ookino/morse-code pull request #1
Opened 2022-01-20 19:03 UTC by yaseerokino

## Project Features

- Decodes a Morse code character, takes a string parameter, and return sthe corresponding character in uppercase (e.g. decode_char(".-") returns "A").
  -Decodes an entire word in Morse code, takes a string parameter, and return the string representation. Every character in a word will be separated by a single space (e.g. decode_word("-- -.--") returns "MY").
- Decodes the entire message in Morse code, takes a string parameter, and return the string representation. Every word will be separated by 3 spaces (e.g.

```ruby
decode("-- -.--   -. .- -- .")
```

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; returns **_"My Name"_**
and

```ruby
decode(".-   -... --- -..-   ..-. ..- .-.. .-..   --- ..-. / .-. ..- -... .. . ...")
```

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; returns the decoded message from the old bottle

2022-01-20 20:25 UTC, rloterh requested changes
## Status: Approved :heavy_check_mark:

Hi Okino & MB Taha,  

Your project is complete! Great job for nailing it right on the first attempt 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- Good ReadMe
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-20 20:25 UTC, rloterh commented on decode.rb
> +def dedcode_word(word)
- [ ] Your app is throwing an error due to a mismatch in method definition and method call. Kindly ensure to improve upon this aspect

**Error:**
![image](https://user-images.githubusercontent.com/12745474/150415921-8c5e5b75-dc40-486f-bc56-f377888ee720.png)

2022-01-21 01:17 UTC, petudeveloper requested changes
Hi @yaseerokino, 

Great work on making the changes requested by a previous reviewer 👏 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-21 01:17 UTC, petudeveloper commented on decode.rb
> +  word
When trying to run your application I am having the following error: `undefined local variable or method `word'`
Please make the necessary changes to your code in order to correct this error. 

Check the image below for a better understanding:
![Screenshot from 2022-01-20 20-08-29](https://user-images.githubusercontent.com/75709904/150447825-ecde6ebc-b218-4659-8df0-b5fb279ece00.png)


**hint:** You are returning the wrong variable name `word`, the only variable you have inside your `decode_message` method is `hint: You are using`.

2022-01-21 03:24 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @yaseerokino and @mbdesigns1989,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-22 02:21 UTC, merged